### ISSUE TITLE
Track outstanding discussions on design of ink!, polkadot.js and substrate

### ISSUE THREAD

**Issue by RoyTimes** [patractlabs/substrate-contracts-book#37]
It would be ridiculously helpful if we can add in a page to keep track of all outstanding discussions. It's always painful to fix a car while it's running. 

Some issues that I'm aware of:
- Issues on error forwarding: https://github.com/patractlabs/redspot/issues/78
- Issues on the rent model of the contract etc.

If it sounds like a good idea to you, I am happy to contribute if someone can put together a list of all these discussion topics, while I can write a brief protocol of contribution and fill in the related issue details and the latest updates from these outstanding github issues in English.

**Comment by atenjin** [comment]
thanks!

**Comment by RoyTimes** [comment]
Let me know when a list is put together. You guys know those issues better than I do. Closing this for now.
